apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: elasticsearch
  name: elasticsearch
spec:
  ports:
  - name: "9200"
    port: 9200
    nodePort: 31000
  selector:
    name: elasticsearch
  type: NodePort
